### ISSUE TITLE
Checklist for 1.3.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#10]
### Implementations
- [x] Add spellbook support for [mystical mayhem](https://github.com/kreaddy/MysticalMayhem). ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/page-4#entry117127028))
- [x] Add spellbook support for [expanded content](https://github.com/ka-dyn/ExpandedContent/). ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/page-4#entry117127028))

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json
- [x] Update mod description
- [x] Update mod version
- [x] New screenshots
- [x] Release description
