### ISSUE TITLE
Checklist for 4.3.0 (draft)

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#103]
## Implementations
- [ ] Add UMM settings to change Isekai Protagonist class base clothing (#101)
- [ ] Change `Killing Intent` into toggle ability (#101)

## Release Tasks
- [ ] Copy localization
- [ ] Update CHANGELOG.md
- [ ] Update README.md
- [ ] Update Info.json
- [ ] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by JohN100x1** [comment]
- UMM option to change default clothes is turning out nicely.

![图片](https://user-images.githubusercontent.com/16169515/226509373-3f411c36-4c95-4229-a5e0-d81a9f0a098c.png)

**Comment by kjk001** [comment]
looks nice

oh I also have a ToDo suggestion:

- [ ] add a request for creative or spellchecking people like fredamora to directly join us here to help with better descriptions

**Comment by JohN100x1** [comment]
@kjk001 Is this a intended or a bug?
> if (shamancapstone != null) {
    ShamanLegacy.Get().LevelEntries.AddToArray(Helpers.CreateLevelEntry(20, shamancapstone));
}

It seems to be different from the other lines

**Comment by kjk001** [comment]
That is a bug, the `ShamanLegacy.Get().LevelEntries =` was lost in some edit and as a result the shaman now gets no capstone

**Comment by kjk001** [comment]
@JohN100x1 I have added a legacy selection for the God Emperor since it was already under debate as part of the rebalance for 5.0 and adding it meant I felt less bad about adding a level restriction to the dual legacy

The paladin bug should be fixed given that I healded by 2d6 after hitting myself with a battering ram spell but I would prefer if someone not me also tests that to verify it.

Also here is a current list on how the restrictions of each legacy are set:
![image](https://user-images.githubusercontent.com/121681604/227594448-dd3f436c-ada7-4d1f-8bb9-c10e9c32106f.png)

So purely in terms of potential versality of available legacies at the moment the hero wins hands down :D

**Comment by Mythalar** [comment]
>Also here is a current list on how the restrictions of each legacy are set

Oh that will hurt some :p
As noted before, I guess the support legacies will be heavily discussed !
IE God Emperor has no access to bard or skald, so only tactician/judge whereas he is buff oriented.

*popcorn*

**Comment by Mythalar** [comment]
You are right, but a quasi deity can also inspire people.
After, stretching the concept, incense synthesizer (and sacred incense) could be thematic...

**Comment by JohN100x1** [comment]
@kjk001
I find the God Emperor legacies a bit restrictive. I would add the magus and sorcerer legacy as available options.

My original idea for the God Emperor is for power fantasy RP and as someone that has an feeling of authority. Skalds and bards make me think of street musicians and don't give the feeling of someone who is a king or a ruler, so even though they are mechanically similar (buffing allies), I want the God Emperor to inspire by presence (rather than by performance).

**Comment by kjk001** [comment]
Knock yourself out with adding what makes sense to you.
I added what based on the description of the archetype made sense to me, I make no claim that every choice was correct.

There might still be options to add or remove and right now there are probably too few 0s on the board.

**Comment by Mythalar** [comment]
Well it's impossible to make some perfect compromise and there it's a good start.

Though I quite vouch for the sorcerer legacy for God Emperor.

**Comment by kjk001** [comment]
Also I am beginning to hate visual studio for adding dependencies whenever it thinks they are needed, even if the only reason it thought that they were needed was because it auto corrected the code I was typing to some completely different reference...

I always forget to remove the dependency after correcting the code.

**Comment by kjk001** [comment]
@JohN100x1 What is the plan for the human heritage, did you want to add it only if the other mod is present or add a compatibility mode?

I also have found one sort of issue, IsekaiFighterTraining and the Fighter Legacies stack so starting at 3th level you quickly rack up a lot of levels in terms of qualifying for fighter feats.

**Comment by kjk001** [comment]
also the white frame problem also affects pet dragons and likely every other custom companion

**Comment by JohN100x1** [comment]
For the human heritage I think we should a `huamn heritage selection` (our human heritage can go inside this) and add this to `HumanRace.m_Features`.
If this works then for compatibility we can check whether to add the `huamn heritage selection` into `HumanRace.m_Features` or into the other mod's human heritage selection.

Also Just to let you know as well, I'm mainly working on two things currently.
1. Adding new dialogue for the Isekai Protagonist. I think I'll add two more dialogue answers (so three in total for this patch). Dialogue is really, really annoying to add since they're all called `AnswerList_0011` or soemthing like that and there's like 20 of them.
2. Updating some OP ability descriptions to be more favorful https://github.com/JohN100x1/WOTR_IsekaiMod/issues/105

This will likely take some time so I won't be done until next week.

> also the white frame problem also affects pet dragons and likely every other custom companion
I fixed this on [my branch](https://github.com/JohN100x1/WOTR_IsekaiMod/blob/JOHN_4-3-0/IsekaiMod/Utilities/ThingsNotHandledByTTTCore.cs#L154)

**Comment by kjk001** [comment]
Then do you want me to take over the human heritage thing?

**Comment by JohN100x1** [comment]
If it isn't too much trouble. Yes.

**Comment by kjk001** [comment]
@JohN100x1 Description still needs flavor Text but it works and I tested the High Human with and without alternate human traits active, so we will be compatible.

**Comment by kjk001** [comment]
On a related note, even though the High School Student background is a background and not a racial trait should we  perhaps still delcare  its bonuses as such, simply because the game seems to actually display those properly rather than just add them to the calculation in the backend?

**Comment by JohN100x1** [comment]
> @JohN100x1 Description still needs flavor Text but it works and I tested the High Human with and without alternate human traits active, so we will be compatible.

Great job!

> On a related note, even though the High School Student background is a background and not a racial trait should we perhaps still delcare its bonuses as such, simply because the game seems to actually display those properly rather than just add them to the calculation in the backend?

The benefit of this (from what I remember) would be extra skill points. It was just a preference how I did it because I didn't want to have two racial bonuses show up when I hover over the stats. So I diagree with it being racial bonuses.

**Comment by Mythalar** [comment]
> On a related note, even though the High School Student background is a background and not a racial trait should we perhaps still delcare its bonuses as such, simply because the game seems to actually display those properly rather than just add them to the calculation in the backend?

Background bonuses are properly displayed as traits bonuses though.

**Comment by JohN100x1** [comment]
@kjk001 Also to let you know. I will do the release on `2023-03-28T21:00:00+0000` so make sure your branch is ready by then.

**Comment by kjk001** [comment]
I also had an idea for a second human heritage:

**Name:**
Isekai Crossbreed Human

**Description:**
Let us be honest, there is a reason why for any mixed race classification it is always enough to name the non human options. 
Because generally it is simply save to assume that the other part of it will be human.
There is no other race, except for dragons, that is as flexible when it comes to its choice of bed partners and none as flexible when it comes to being fertile when crossbreeding and realistically by now there are no true pure humans left because everyone is at least (1/2)^100 something else. 
And no matter how close to 0 that number is it is not 0 and for some reason in you all that blood became active as if you were a full member of that species.

**Mechanics:**
```
bp.AddComponent<AddFacts>(c => {
                    c.m_Facts = new BlueprintUnitFactReference[] { 
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("b7f02ba92b363064fb873963bec275ee"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("64e8b7d5f1ae91d45bbf1e56a3fdff01"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("c4faf439f0e70bd40b5e36ee80d06be7"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("25a5878d125338244896ebd3238226c8"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("ef35a22c9a27da345a4528f0d5889157"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("1dc20e195581a804890ddc74218bfd8e"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("fd188bb7bb0002e49863aec93bfb9d99"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("4d4555326b9b7144f93be1ea61337cd7"),
                        BlueprintTools.GetBlueprintReference<BlueprintUnitFactReference>("5c4e42124dc2b4647af6e36cf2590500")
                    };
                });
```
Or in non mechanical terms, it adds all other races onto you, you don't get their heritage selections, but their racial stat bonuses and count as a member in terms of qualifying for feats(I tested and this works).

Though purely from a balance standpoint this should probably be changed to a selection that allows you to pick 2-3 other races whose heritage is particulary active in you. Because if you take the destiny beyond birth feat the total stat bonus actually rises above that of the high human.

**Comment by kjk001** [comment]
I also think my current to do list for this patch is empty, those bug fixes still open up there were done and just need verification by a second tester before the check mark is set.
Besides that I am now playing around with potentially horrible ideas like the one directly above.

**Comment by Mythalar** [comment]
>Or in non mechanical terms, it adds all other races onto you, you don't get their heritage selections, but their racial stat bonuses and count as a member in terms of qualifying for feats(I tested and this works).

So just racial bonuses/penalties to stats?
It's not so uber unbalanced per see, looking at the Isekai High Elf (love it ^^) and the +4 spell casts which is really powerful and unique (even if useless with the Unlimited Power OP ability)

**Comment by kjk001** [comment]
don't forget the second part, with the way it adds the other race onto you, you count as a member of that race in terms of qualifying for feats.

So give my human that dhampirs bite attack or the celestial companion of an aasimar...

**Comment by Mythalar** [comment]
Yes I see.
Most are skill bonuses and I'm quite sure there is no bite attack outside actual race heritage/trait but there are some nice possibilities like cautious fighter.
Some could be litteral trap like vulpin pounce though.

Edit: my bad there is a bite attack feat as a half-orc. Does it work even if it does not give stat bonus since it's a +2 you choose?

**Comment by kjk001** [comment]
To clarify it adds the fixed boni and mali of each race, not those added by heritages on top of them.
Dhampir get Blood Drinker thrice a day as a bite attack that heals you, orc gets a regular bite attack, ...

so +2 con and wis  and -2 charisma for dwarf  +2 Int and -2 con for elf, ...

**Comment by Mythalar** [comment]
Ok I understand, can be quite interesting to test!

**Comment by kjk001** [comment]
I had to do one more bugfix because my new characters just hit level 5 and I found out that the no archetype condition always gives a false positive if the class is not set in it.

**Comment by JohN100x1** [comment]
@kjk001 I made a [small fix](https://github.com/JohN100x1/WOTR_IsekaiMod/commit/3838802ba08d41a1b172271a22a7a0ad9cff6c24) to the code in the legacy ability selection on my branch because the logs kept saying the class blueprint didn't exist.

On another note I've finished updating descriptions for some OP abilities. All that's left for me to do is the 2 extra dialogue options and to write up a description for the isekai high human.
- For the paladin bug I think we can just ignore save campatibility.
- For the bugged Mythic Class Feature selection I will work on a fix for it.

Anymore unimplemented features can go into 5.0.0.
4.3.0 should be good for release in 2 days.

**Comment by JohN100x1** [comment]
> For the loops inside the archetype selections your change should actually slightly slow the code down because it has to get the reference over and over(though that slowdown should be to the pointof 1/1000000000 seconds or something equally ridiculously small, so who cares).

For some reason I thought I was moving the variable into an IF statement. I will reverse that change. Thanks for letting me know.
