### ISSUE TITLE
Checklist for 5.0.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#109]
## Implementations
- [x] Add `Supermassive` Special Power.
- ~~Add `Excalibur` Special Power.~~
- [x] Add `Sigma Strike` Special power that implements `WeaponCriticalEdgeIncreaseStackable`.
- [x] Add `Power leveling` OP ability that increases exp gain using `AddPlayerLeaveCombatTrigger`.
- [x] Add `Signature Strike` to signature move selection.
- ~~Add `Celestial Realm` and `Shadow Realm` as OP abilities (require level 15).~~
- [x] Update TabletopTweaks-Core requirement to 0.5.15.
- [x] Add some wuxia/murim-like backgrounds (#114)
  - [x] Added `Demonic Cultivator` Isekai background. 
  - [x] Added `Enlightened Sage` Isekai background.
  - [x] Added `Musician` Isekai background.
  - [x] Added `Rationalist` Isekai background.
- [x] Class Reworks
  - #108
  - #123
- [x] Rework `Aura of Righteous Wrath`.
  - [x] Add variants
  - [x] Remove effect on additional limbs.
- [x] Change `Killing Intent` into a toggle ability (#101)
- [x] Nerf `Exceptional Weapon` feats to no longer work with additional limbs (remember to update description)
- [x] Nerf `Beta Tester` initiative bonus from 10 -> 4.
- [x] Nerfed Magical Amplification spell dice from d12 -> d10.
- [x] Buffed `Gamer` background from +4 to +8
- [x] Fix `Reflect` to ignore attacks from owner (#125)
- [x] Remove True Smite and True Mark from paladin legacy. (#107)
- [x] Remove redundant `Kinetic Power` Special Power (#107)
- [x] Remove redundant `OverpoweredAbilitySelection2` and just use `OverpoweredAbilitySelection` instead.
- [x] Remove alignment restrictions for Isekai `Channel Positive Energy` and `Channel Negative Energy`.
- [x] Update icon for `Exceptional Feats`.
- [x] add crossbreed human to human heritages
- [x] #122 
- [x] #128 
- [x] Bugfix, selection array initilization logic seems to differ either due to other mods, game version, or just because; making the use of the Features reference proxy array questionable, so instead the underlying m_AllFeatures array needs to be used everywhere #129 

## Pre-Release Tasks
- [x] Update LocalizationPack.json
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by JohN100x1** [comment]
Yeah I guess I could add an evil version. I was thinking about what you said about adding prerequisites and this one seemed to make sense.

**Comment by kjk001** [comment]
Chaotic and Lawful would also make sense as options since those are the 4 choices smite usually goes by.

Or we are simply less strict and say Righteous wrath is centered at lawful good and will empower anyone within 2 steps (so neutral good, chaotic good, Lawful neutral, True Neutral, Lawful Evil) While the counterpart is centered on chaotic evil with a similiar restriction.

Oh and obviously having one would block you from picking the other to prevent any true neutral cheaters from gaming the system...

**Comment by kjk001** [comment]
Splitting it along the smite options might be a really good idea because that way each aura could also have its own damagetype.

Good would be holy, evil negative, Lawful Fire, Chaotic Air, or something like that...

**Comment by Nerin3** [comment]
I was thinking about it, but somehow legend unlocks you to level 40, would it be possible to do the same with IP and make it a class with actually 40 levels of progression. (if not possible then maybe a prestige class that you can pick after reaching 20 lvl with protagonist?

**Comment by JohN100x1** [comment]
It shouldn't be too hard to add a prestige class, but I wonder what we should call it?
Something like `Isekai Protagonist+` would be so uncreative.

That makes me think about an off-topic question, how do most isekais end anyway? Like all the Isekais I've seen are still on-going.

**Comment by Nerin3** [comment]
That's the problem with Light Novel type of writing, they drag on for so long that usually authors stop before they reach final conclusion, or the story mostly ends with protagonist becoming existence equal to god. There are some exceptions where it just ends with their death and admitting they lived a satisfying life.

**Comment by Nerin3** [comment]
As for Prestige class for IP, maybe Awakened Protagonist.

**Comment by kjk001** [comment]
since Nerin mentioned the idea yesterday I had some thought on mechanics for the Prestige class..

Easy progression choice, continuing to grant an extra basic feat at every even level.
Grant an additional  overwhelming feat every 4-5 levels.
Grant an "Impossible Feature" at every odd level, this feature would allow the player to select or reselect a class feature of the IP and its archetypes. For example since you need to pick what to buff in beach episode you could make a second choice using this, or perhaps you want some of the additional attacks restricted to Edge Lord as a Hero, or want your God Emperor to use Charisma for everything the way the Hero does?

With every archetype getting a choice of legacy I was thinking of debuffing the Dual Option a bit by not just restricting it to be available only for level 5+ or perhaps even 10+ but also adjusting the dual progression that way as well.
So your second choice of legacy would only get 15 (or 10) levels amongst the original 20 and it would be only by going legend and picking this prestige class that you could get the final levels.

For non legends this would also make it a lot more important of a choice what you pick for first rather than second legacy.

**Comment by kjk001** [comment]
See my statement above on keeping neutral characters from gaming the system.
 Depending on what options we add we have different options on who can pick it and who it can affect while remaining fair to everyone.
If we go by the 4 smite options then centering them around the neutral option of their axis and allowing only 1 step away from it would be balanced.
With just two options I think we always leave a hole where a specific build feels that they are limited in some way, because the lawful evil character might consider lawful to be more important than evil, so why can he buff the chaotic neutral rogue but not the lawful good paladin despite them being closer?

**Comment by kjk001** [comment]
Actually I think that means we need to keep the buff effect the same and delcare it non stackable, that way even if you are under the effect of two auras only the first counts...

**Comment by ThePiggyGalaxy** [comment]
> It shouldn't be too hard to add a prestige class, but I wonder what we should call it? Something like `Isekai Protagonist+` would be so uncreative.
> 
> That makes me think about an off-topic question, how do most isekais end anyway? Like all the Isekais I've seen are still on-going.

most end by defeating the villain and either going home or staying in this world to live happily ever after.



> See my statement above on keeping neutral characters from gaming the system. Depending on what options we add we have different options on who can pick it and who it can affect while remaining fair to everyone. If we go by the 4 smite options then centering them around the neutral option of their axis and allowing only 1 step away from it would be balanced. With just two options I think we always leave a hole where a specific build feels that they are limited in some way, because the lawful evil character might consider lawful to be more important than evil, so why can he buff the chaotic neutral rogue but not the lawful good paladin despite them being closer?

yeah, something like [Divine Anathema](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Divine+Anathema) should be most balanced, but that would also be rather overpowered for neutral characters won't it?

**Comment by progregret** [comment]
Hello! Is it possible to remove alignment restriction on the Villain archetype or add a feat/backgroud/OP Ability that allows taking this class with good aligment (name like Heel–Face Turn)? I really want to play it, but standard ToyBox option doesn't work at all.

**Comment by kjk001** [comment]
the current cillain is being split into two archetypes in this patch, overlord and mastermind with mastermind not being alignment restricted, so depending on what your reason for wanting to pick the current villain is that might already do it for you

**Comment by progregret** [comment]
> the current cillain is being split into two archetypes in this patch, overlord and mastermind with mastermind not being alignment restricted, so depending on what your reason for wanting to pick the current villain is that might already do it for you

well, i really like double Overpowered Ability aka Villainous Overpowered Ability

**Comment by JohN100x1** [comment]
If you're mostly picking the auto-metamagics the new `Mastermind` subclass coming in 5.0.0 should be suitable.
Otherwise you need to be evil and choose the new `Overlord` subclass (also coming in 5.0.0).
You can see the changes so far here. Not all changes are listed yet.
- #123
- #108

### Still work in progress
![图片](https://user-images.githubusercontent.com/16169515/230509094-0ee19338-f3ab-40e2-8e75-4531a01cef94.png)

If you know some C#, you can even build your own version.

**Comment by progregret** [comment]
> If you're mostly picking the auto-metamagics the new Mastermind subclass coming in 5.0.0 should be suitable.
Actually, it's almost perfect. If there was a way to add "Mythic Spells", it would really greant. In fact, this is why I want double OA - collect all spells for ultimate spellbook :)

> If you know some C#, you can even build your own version.
I know a little bit of C# and understand what needs to be edited specifically (I even found out what exactly needs to be changed), but I'm not sure how to correctly compile the code into a mod-zip file.

**Comment by kjk001** [comment]
you don't, the zip file is a zipped version of the mod folder that is installed under D:\Steam\steamapps\common\Pathfinder Second Adventure\Mods or whatever your game Mod folder is.
If you compile the code locally it will be installed directly to that folder with no need to zip it first.

**Comment by kjk001** [comment]
Well you can turn off the automatic installation because that is done by: 
```
<PropertyGroup>
    <PostBuildEvent>(robocopy "$(TargetDir) " "%25WrathPath%25\Mods\IsekaiMod\ " /s /e )^&amp; IF %25ERRORLEVEL%25 LEQ 1 exit 0</PostBuildEvent>
  </PropertyGroup>
```
as a compiler directive and then it will only be build to a build directory in the project from where you could copy it manually or zip it if you feel that you need to involve the modfinder tool by dropping it in

**Comment by kjk001** [comment]
Also, as far as I can see there are 4 overpowered feat selections which would allow you to pick a mythic spellbook to be added, assuming that option hasn't also been added to the metamagic feats given its magical nature...

**Comment by kjk001** [comment]
I believe someone still wanted the wisdom based version of kineticist for the god emperor, besides that feedback for names and descriptions for this version was fairly low anyway :( 
I think about the only thing really left to do in this version is updating the availability chart for the new sub classes...

**Comment by Mythalar** [comment]
> I believe someone still wanted the wisdom based version of kineticist for the god emperor

Guess that was me, was looking for a godling throwing lighting everywhere like a mini Zeus ^^
But if it cannot be done then...

**Comment by kjk001** [comment]
@Mythalar 
It can be done, it is actually a lot less work than most of the asked for customisation ideas so far because all it needs is the implementation of a single newly made burn feature that overrules the main stat to Wisdom and copies pretty much everything else from an existing burn feature.

The biggest problem with it is that all affected blasts have to be defined in the feature, which can lead to problems with expanded elements depending on when in the patchorder it is done.

The description is actually the bigger problem as far as I am concerned because the text of both the Custom Burn feature and the archetype should then make you sound appropriatly divine and any idea I come up with is zeus (or similiar) based and let us be honest he is a bad example for wisdom and makes a very good case for why charisma should have been the divine stat instead...

**Comment by Mythalar** [comment]
(Crossed posts with the legacies thread I guess)

@kjk001 
Okay I thought you even could more or less copy/paste a class or subclass so you would not have to manually assign/modify too many things.

On the description side I partially disagree with you.
You are right that Zeus and quite a bit of similar gods are not paragon of wisdom (greeks and latin gods were made similar to mankind after all :p ) but the Psycho wisdom mechanic does not dwells into this.

The actual description and rules books emphasize this subclass as an indivudual that contains the power flow of the elements within his mind instead of within his physical body, hence the constant straining and he's then exposed to emotional outbursts.
So it's not sage wisdom, but more of concentration/discipline, whereas charisma is all innate.

In my mind (...) it does make sense as a (divine) power that is growing inside the character and that he must learn to wield alongside his others abilities, more so than some other kineticist subclasses.

**Edit** : From stat description "_Wisdom describes a character’s willpower, common sense, awareness, and intuition._"
I think willpower is precisely what define a god in those settings, they are just powerful wills without true actual bodies.

Don't know how do you and @JohN100x1 see this?

**Comment by kjk001** [comment]
I am not disagreeing with the mechanical standpoint, I am saying that I am having problems coming up with a clever description for both to make them sound like features for a divinely touched person growing like that because all my ideas circle back to gods who are terrible examples for that...

**Comment by Mythalar** [comment]
Oh, will think about something revolving over power surge in the legacies topic for archetype and mind burn.

**Comment by JohN100x1** [comment]
I won't be of much help with the descriptions. I've spent all my creative power trying to think of names for the reworked `Aura of Righteous Wrath` variants.

**Comment by kjk001** [comment]
@JohN100x1 so apparently multiple classes in a ContextRankValueType.Classlevel do work?
I am fairly sure that was the first thing I had tried though and that the whole reason why I added a second version of the context was because my heal with the paladin legacy had not increased with that, when I just retried it though it did work now and now it does work even if I do not change its type to sum with multiple classes in the same array?
Either way I added some additional breakpoints for the method to realise that it retravels already patched features and abort and the change in handling ContextRankProgressions should now also cover domainpowers...

**Comment by kjk001** [comment]
anyway with that I am done for today and going to bed good night

**Comment by JohN100x1** [comment]
good night 😴
