### ISSUE TITLE
Checklist for 1.4.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#12]
### Implementations
- [x] Add Villain archetype (#11).
- ~~Add Avatar archetype (#11).~~ (delayed for design considerations)
- [x] Add drake pets from expanded content ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/page-5#entry117202698))

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json
- [x] Update mod description
- [x] Update mod version
- [x] New screenshots
- [x] Release description
