### ISSUE TITLE
Checklist for 1.5.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#17]
### Implementations
- [x] Add OP ability that gives you every buff imaginable (#2)
- [x] Add Isekai Heritages (#3)

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json
- [x] Update mod description
- [x] Update mod version
- [x] New screenshots
- [x] Release description
