### ISSUE TITLE
Checklist for 1.6.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#19]
### Implementations
- [x] Add a feature that increases character encumbrance (#1)
- ~~Add a second background selection (#1)~~ (Cannot implement this due to background limitations)
- [x] Remove crit immunity bypass in description for `alpha strike` and `godhood`.

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json
- [x] Update mod description
- [x] Update mod version
- [x] New screenshots
- [x] Release description
