### ISSUE TITLE
Checklist for 1.7.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#21]
### Implementations
- [x] Implement otaku, demon lord, gamer backgrounds (#4)
- [x] Implement aqua, ristarte, admin D Deities (#14)

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
