### ISSUE TITLE
Checklist for 1.8.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#23]
### Implementations
- [x] Implement heritage for Dhampir (#3)
- [x] Add extra Dialogue (#15)
- [x] Buff Isekai Succubus heritage
- [x] Buff God Emporer
- [x] Update background bonus type
- [x] Fix Villain spellbook merge

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
