### ISSUE TITLE
Checklist for 1.9.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#27]
### Implementations
- [x] Add deathsnatcher animal companion
- [x] Extra wing options (#3)
- [x] Fix loremaster spellbook selection for isekai protagonist
- [x] Fix hellknight signifier spellbook selection for isekai protagonist

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by jedi7000nathan** [comment]
Playful Darkness when?

**Comment by JohN100x1** [comment]
soon
![image](https://user-images.githubusercontent.com/16169515/202007943-97bd9648-eac7-45e1-b6fa-d81ab8c675a0.png)

**Comment by JohN100x1** [comment]
still sorting out the progression sheet and adding some feats on it

**Comment by jedi7000nathan** [comment]
My only question is what do we do for its equipment

**Comment by JohN100x1** [comment]
Right now the slots it has is the same as animal companion.
The equipment that playful darkness has is quite generic except maybe the ring of evasion so I don't think the deathsnatcher companion should with any equipment.

![image](https://user-images.githubusercontent.com/16169515/202018932-81e1aaf9-2814-45db-8e38-d1c24c49f97a.png)
![image](https://user-images.githubusercontent.com/16169515/202019521-f0ffba00-97b2-451c-be8c-6fe933784550.png)
