### ISSUE TITLE
Checklist for 1.10.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#28]
### Implementations
- [ ] Add keyword immunity character development feats (#1)
- [ ] Add radiance upgrade dialogue (#29)
- [ ] Change Description for `Isekai Protagonist`

### Release Tasks
- [ ] Copy localization
- [ ] Update CHANGELOG.md
- [ ] Update README.md
- [ ] Update Info.json
- [ ] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by JohN100x1** [comment]
Move all implementations to 2.0.0
close #28
