### ISSUE TITLE
Checklist for 2.0.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#30]
### Implementations
- [x] Add exceptional feats
- [x] Rework Training Arc to have overpowered abilities
- [x] Rework existing character development feats
- [x] Add channel positive and negative energy feats
- [x] Add mythic feats to exceptional feats
- [x] Add Elf Heritage
- [x] Gnome Heritage ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=117840633))
- [x] Add Hero archetype (#11)
- ~Add kinetic blast feats~ (**Delayed for 2.2.0**)
- [x] Add keyword immunity character development feats (#1)
- [x] Add radiance upgrade dialogue (#29)
- [x] Change Description for `Isekai Protagonist`
- [x] Remove `Winner` feature

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by JohN100x1** [comment]
Delaying adding kinetic feats because it will take too long.

**Comment by jedi7000nathan** [comment]
Understandable. What do you think will make the cut for 2.0 and else will likely be delayed

**Comment by JohN100x1** [comment]
everything else should be added in 2.0
the issue with the kineticist stuff is that i have no idea how it works. i haven't even played the class before.
