### ISSUE TITLE
Checklist for 2.1.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#34]
### Implementations
- [x] Integrate spellbook merge mod (#32)
- [x] Add ability to refresh spells per day ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118027563))
- [x] Additional OP abilities (#2)
- [x] Additional background (#4)
- [x] Feats to help summoners ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=117914303))
- [x] Make content group for exceptional feats

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
