### ISSUE TITLE
Checklist for 2.2.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#35]
### Implementations
- [x] Add kinetic blast feats (delayed from #30)
- [x] Add nocticula and Mephistopheles for summon calamity ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118398563))

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
