### ISSUE TITLE
Checklist for 3.0.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#38]
### Isekai Protagonist rework
- [x] Add `Starting Weapon`. lvl 1 feat to add chosen weapon (#24)
- [x] Add all spells to spellbook ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118605498))
- [x] rework progression
- [x] Add `Signature Ability` feature. Increases spell damage and spell DC. Can be chosen instead of `Signature Attack`.
- [x] Rename `Character Development` to `Special Power`.
- [x] replace harem magnet with summon harem ability: summon a succubus, astral deva, nymph, etc...
- [x] Replace `True Main Character` with `Second Reincarnation`.

### Edge Lord rework
Description: Melee focus, extra attacks, buffed attacks
- [x] Buffed `Extra Strike` to increase the number of offhand attacks aswell ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118585093))
- [x] rework `Extra Strike` using custom component that scales with ranks. See `BuffExtraAttack` and `BuffAllSavesBonus` for reference.

### God Emperor rework
Description: High stats, ally buffing auras
- [x] rework progression (#48)
- [x] Add `Celestial Realm`. Damage conversion to divine. ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118328893))
- [x] Rename `protective aura` to `Aura of Golden Protection`.
- [x] Rename `Glorious aura` to `Aura of Majesty`.
- [x] rework `God Emperor` to steadily progress with resistances and stats (#48)

### Hero rework
Description: charisma focus
- [x] rework progression
- [x] Add `True Mark` ability to `Hero` Archetype progression. ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118132123))

### Villain rework
Description: Magic focus, More OP abilities
- [x] Rework Villain Progression
- [x] Change Villain into Arcanist-like caster (#40)

### Exceptional feats
- [x] rework exceptional weapon to be activatable abilities. Should also enchant additional limbs.

### Special powers (formerly character development feats)
- [x] Add `Mythic Special power` to mythic abilities.
- [x] Add `Armor Saint`. No speed penalty for armor, reduce armor check penalty to zero, increase max dex bonus by 20.
- [x] Add `Summon Beast`. Can summon a hydra, minotaur, or owl bear, or Roc.
- [x] Add `Aura of Divine Fury`. buff allies attack damage and spell damage.
- [x] Add `Killing Intent`. Apply fear, shaken, and cowering to enemies.
- [x] Add `Armor of Strength`. Get natural armor bonus to AC equal to strength modifier.
- [x] Add `Omega Strike`. special power that implements `AttackTypeCriticalMultiplierIncrease`
- [x] Add `Magical Amplification`. special power to change spell damage dice to d12. ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118328893))
- [x] Change `Body strengthening` to be DR 1/- per level. No prerequisites.

### Overpowered Abilities
- [x] Add `Supreme Being`. All attributes become 30. ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118638338)). Implement custom component to alter stats.
- [x] Add `True Resurrection` (#2)
- [x] Add Playful Darkness to `Summon Calamity` ability.
- [x] rename `Interdimensional bag` to `Infinite Inventory`.

### Fixes
- [x] Fixed `Dupe Gold` Ability to give correctly give 1 million gold instead of 100 thousand gold.
- [x] Fix `Exceptional Summoning` feats not applying to summons from spells without the `Summoning` descriptor.

## Post-Implementation Tasks
- [x] Remove redundant properties
- [x] Fix `Summon Harem` spawning on same point
- [x] Fix prebuild

## Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
