### ISSUE TITLE
Checklist for 2.3.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#41]
### Implementations
- [x] Add Isekai High Elf.
- [x] Add Isekai Wood Elf.
- [x] Rename Isekai drow to Isekai Dark Elf, rework stats ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118286063))
- [x] Character development feat to increase spell DC ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118328893))
- [x] Exceptional feat that adds elemental damage ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118328893)) (#1)
- [x] Arcane Trickster "Surprise Spells" called `Sneaky Magic` ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118328893))
- [x] `Auto Selective` OP ability ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118328893))

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
