### ISSUE TITLE
Checklist for 2.4.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#45]
### Implementations
- [x] More dialogue options (#15)
- ~~Add Infusion discovery ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118487273))~~ cannot implement due to hard-coded mechanic
- ~~Add magus spells ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118487273))~~ bladed dash does not exist in game
- [x] Super Buff ability with no claw attacks ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=118574663))
- [x] Add sneak attack prerequisite to `Sneaky Magic`
- [x] Very fast movement changed to untyped bonus
- [x] Insert exceptional feat selection to first for `Bonus feat`
- [x] Change `Isekai Protagonist`, `Edge Lord` and `Villain` to be arcane casters (visual only). (#40)

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

### Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
