### ISSUE TITLE
Checklist for 1.1.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#5]
### Implementation
New Backgrounds:
- [x] `Highschool Student`: Adds +1 to all attributes. (#4)

New Character development feat:
- [x] `Exceptional Summoning`: gives your summons +100 HP, +10 AC, +10 Saving throws, and +10 Attack. (#1)

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] New screenshots
- [x] Update mod description
- [x] Update Repository.json
