### ISSUE TITLE
Checklist for 3.1.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#53]
## Implementations
- [x] Add `BlueprintFeatureReplaceSpellbook` for:
    - `Arcane Trickster`
    - `Mystic Theurge`
    - `Dragon Disciple`
    - `Eldritch Knight`
    - `Winter Witch`
- [x] Add `Aura of Righteous Wrath`. OP ability to give allies sneak attack, extra attack, and damage dice within an area.
- [x] Change summoning feats to allow for melee and caster summons to be buffed. ([link](https://forums.nexusmods.com/index.php?showtopic=12204503/#entry118965763))
- [x] Add `Super Buff` dismiss ability ([link](https://forum.nexusmods.com/index.php?showtopic=12204503/#entry119026278))
- [x] Change `Supersonic Combat` and `Graceful Combat` to affect ranged weapons. ([link](https://forum.nexusmods.com/index.php?showtopic=12204503/#entry118944518))

## Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
