### ISSUE TITLE
Checklist for 3.2.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#57]
## Implementations
- [x] Add `Reflect` Special Power (#2)
- [x] Add option to disable `Isekai Protagonist` class for companions and mercenaries.
- [x] Change `Grasp Heart` to `Instakill`. Buffed version that bypasses death immunity.
- [x] Change `Extreme Speed` to apply to allies within 40 feet
- [x] Change OP abilities to be allowed for all classes
- [x] Fix `Nascent Apotheosis` to DR per level instead of per 2 levels
- [x] Fix `Second Reincarnation` missing buff
- [x] Fix game breaking bug when DLC3 is missing

## Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
