### ISSUE TITLE
Checklist for 3.3.0 (draft)

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#59]
## Implementations
- [ ] Add composite blasts and infusions for `Kinetic Power` special power.
- [x] Fix `Omega Strike` to apply to touch attacks.

## Release Tasks
- [ ] Copy localization
- [ ] Update CHANGELOG.md
- [ ] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by JohN100x1** [comment]
move features to #71
