### ISSUE TITLE
Checklist for 1.2.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#7]
#### ~~New Heritages~~
- ~~Isekai Angel (#3)~~ (delayed for a later update)
- ~~Isekai Succubus (#3)~~ (delayed for a later update)
#### New Character development feature
- [x] Feature that adds an animal companion ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=117028648)) (implement for archetype without character development features)

#### New deity
- [x] Truck-kun ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=116990313))

### Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json
- [x] Update mod description
- [x] Update mod version
- [x] New screenshots
- [x] Release description
