### ISSUE TITLE
Checklist for 4.1.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#81]
## Implementations
- [x] Add Areshkagal to `Summon Calamity`. ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=120817068))
- [x] Add `Isekai Furry` kitsune heritage. ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=120883398))
- [x] Add `Class Legacy` as a signature class feature for the Isekai Protagonist
- [x] Add `None` option for animal companion (#79)
- [x] Add Icon for `Legacy` and `Dual Legacy`.
- [x] Buff `Killing Intent` to 1d4 rounds ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=121459875))
- [x] Change `Legacy` and `Dual Legacy` to only be allowed to be selected once. (#83)
- [x] Rename `Legacy Class Feature` to `Legacy`.
- [x] Rename `Dual Class - Legacy Class Feature` to `Dual Legacy`.
- [x] Fix Deathsnatcher default name.
- [x] Fix `Supreme Being` to allow base stat increases.
- [x] Fix `Instakill` spell penetration modifier. (#84)
- [x] Fix `Dread Knight Legacy - Dread Lord` not appearing in selection. (#87)
- [x] Remove `Sneak attack` as a signature class feature for the Isekai Protagonist

## Release Tasks
- [x] Copy localization
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by JohN100x1** [comment]
@kjk001 If there's anything you want to add for 4.1.0 release you can add it to the checklist here.

**Comment by JohN100x1** [comment]
Excellent. 4.1.0 should be done this week when I finish implementing and testing the new changes.
