### ISSUE TITLE
Checklist for 4.2.0

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/WOTR_IsekaiMod#88]
## Implementations
- [x] Add automagics from TabletopTweaks-Base (#86)
- [x] Add UMM option for (#96)
- [x] Add UMM option to restrict Exceptional feats, Mythic OP abilities and mythic special powers to the Isekai Protagonist Class (#104)
- [x] Rework UMM settings UI (#97)
- [x] Fix typos and incorrect grammar (#90)
- [x] Fix Channel Energy and Other Features using its method to declare progressions (#92)
- [x] Fix `Channel Positive Energy` Special Power to work with selective channel (#95)
- [x] Fix missing dialogue for drow ambush encounter.
- [x] Fix `Kinetic Power` fire avatar eruption ability animation.
- [x] Fix `Martial Artist` nunchaku weapon proficiency ([link](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/101#issuecomment-1475248456)).
- [x] Update mod support for expanded content.
- [x] Bugfix Patch Dread Lord Legacy for Expanded Content Update 0.5.3

## Optional Implementations (KJK: if I don't get them done on time they will simply be moved to the next patch)
- [x] Kinetic Legacy - Soulbinder (#83)
- [x] Kinetic Legacy - Noble Soul (#83)
- [x] Fighter Legacy - Basic Fighter
- [x] Monk Legacy - Daoist Martial Artist
- [x] Monk Legacy - Fist of a Dragon
- [x] Skald Legacy - Metal Singer
- [x] Skald Legacy - Silver Tongue
- [x] Skald Legacy - The Voice
- [x] Shifter Legacy - Ditto
- [x] Shifter Legacy - Stinger
- [x] Shifter Legacy - Shapeshifted Baby Dragon

## Pre-Release Tasks
- [x] Update LocalizationPack.json
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by JohN100x1** [comment]
@kjk001
Feel free to edit the checklist if you have more things you want to add

**Comment by kjk001** [comment]
@JohN100x1 does the automatic  generation of new guid values still work for you?

For some reason I got 
[IsekaiMod] Added:  - FighterBasicIsekaiLegacy
When it should create a new Id every time it is run with no id set yet.

**Comment by JohN100x1** [comment]
There's automatic guid generation? I've always had to add new guid everytime.

**Comment by kjk001** [comment]
there used to be, it works the same way it does for strings that it then gives you a new line:
[IsekaiMod] WARNING: Generated New Localized String: 1040c2d59d954496a6b4f99402789de1:FighterBasicIsekaiLegacy.Name

The result is written into the blueprints.json under auto generetad IDs and should be moved from there to the other section asap because any value in there is not final and can just be reassigned at random, my magus guid changed three times during development...

**Comment by kjk001** [comment]
speaking of guid that can just change: expanded content changed one of theirs again in patch 0.5.3 so the Dread Knight will break again

**Comment by JohN100x1** [comment]
> speaking of guid that can just change: expanded content changed one of theirs again in patch 0.5.3 so the Dread Knight will break again

troublesome :sweat:

**Comment by kjk001** [comment]
Is is not our fault and thanks to the idea I just tested for the fighter legacy also not our problem in the future as the check on our part will simplify to is the guid of the class there and if yes then build based on the class.

The bugreports about changed features breaking saved games because a guid of one of their features no longer exist are then their problem...

This new way is also better for us because it will no longer matter to us what version of the other mod the person is running, they  will simply get the Dread Knight they should expect based on that version.

```
public static BlueprintProgression PatchClassProgressionBasedOnRefClass(BlueprintProgression prog, BlueprintCharacterClass refClass) {
            prog.IsClassFeature = true;
            prog.m_Classes = new BlueprintProgression.ClassWithLevel[] {
                    new BlueprintProgression.ClassWithLevel {
                        m_Class = IsekaiProtagonistClass.GetReference(),
                        AdditionalLevel = 0
                    }
                };
            prog.AddComponent<ClassLevelsForPrerequisites>(c => {
                c.m_FakeClass = refClass.ToReference<BlueprintCharacterClassReference>();
                c.m_ActualClass = IsekaiProtagonistClass.GetReference();
                c.Modifier = 1.0;
            });
            var referenceLevels = refClass.Progression.LevelEntries;
            prog.LevelEntries = new LevelEntry[] { };
            foreach (var referenceLevel in referenceLevels) {
                BlueprintFeatureBaseReference[] features = referenceLevel.m_Features.ToArray(); ;
                prog.LevelEntries = prog.LevelEntries.AddToArray<LevelEntry>(Helpers.CreateLevelEntry(referenceLevel.Level, features));
            };

            var referenceUIGroups = refClass.Progression.UIGroups;
            prog.UIGroups = new UIGroup[] {
                };
            foreach (var referenceUIGroup in referenceUIGroups) {
                prog.UIGroups = prog.UIGroups.AddToArray<UIGroup>(referenceUIGroup);
            }
            prog.m_UIDeterminatorsGroup = new BlueprintFeatureBaseReference[] { };
            var referenceUIDeterminators = refClass.Progression.UIDeterminatorsGroup;
            foreach (var UIDetermin in referenceUIDeterminators) {
                prog.m_UIDeterminatorsGroup = prog.m_UIDeterminatorsGroup.AddToArray<BlueprintFeatureBaseReference>(UIDetermin.ToReference<BlueprintFeatureBaseReference>());
            }
            return prog;
        }
```
I'll try to move the Kineticist over to this generalized method as well, then write a version for archetypes and then we will only have to manage our custom legacy progressions as the base class versions are automatically generated except for their name and description.

**Comment by kjk001** [comment]
So the Patch Method works for the Kinetic Lord as well, but quite a few feats programmed as part of Dark Codex have Bad Component References that cause Nullpointer Exceptions when crawling them for patching, full list follows:
_[IsekaiMod] ERROR: Unpatachable Feature= 637329bf936244668c55d81985c4eaf8name= Venom Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= e9021412e87847b3b104d4d31bfe5403name= Venom Infusion, Greater at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 96360bedde8648a8a6762e2de41b60a5name= Disintegrating Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= e9cf588e2ef64fb68d0ec8c566e8b294name= Dampening Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 8662ccb8dd484a2f8139d46621c641fdname= Enervating Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 3ae954ad56a2497b92fada3dc493b4e1name= Pulling Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= e53160d091914d50bfc1d8d4fa482e30name= Unnerving Inufsion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 922fd10e3e994d7793821da1583cdfeaname= Vampiric Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 987dc633dbae49b0adc11cd9c5672553name= Weighing Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 1cd0cd60997d4288be1fc85f753e53dename= Spore Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= fdc63fd61b794e40ba3c5446ba8ea1c2name= Toxic Infusion at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 56567887f604473797dc8223c68999daname= Toxic Infusion, Greater at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 94341284499343c0b5652f082bd677d1name= Self Telekinesis, Greater at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= c03b1a6d297843c584b763378024ea7aname= Telekinetic Finesse at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 8d3e9c13037d4d4f944887b517bbf86bname= Gravity Control, Greater at level= 2 reason= Object reference not set to an instance of an object
[IsekaiMod] ERROR: Unpatachable Feature= 70322f5a2a294e54a9552f77ee85b0a7name= Metakinesis — Empowered at level= 1 reason= Object reference not set to an instance of an object_
I tried and the blasts work fine and nothing on this list should actually have Features hidden behind them that require patching but based on his repository code I can't even easily tell if he adds a factRef or a Ressource with a required value not initialized on them.

Ah well, it works even if those messages are irritating to me.

**Comment by kjk001** [comment]
I updated the loop prevention logic of PatchClassIntoFeatureOfReferenceClass a bit as thief and fighter together caused a bit too much load time for my liking when running them through that.

Ah well, as long as the legacy is a vanilla class or archetype it is now very easy to add.

Just set name and description, tell the Methods what the reference class or archetype is and then set what Isekai Archetypes should get the legacy.

**Comment by kjk001** [comment]
and I was right in that archetypes are a hell on their own.
Scaled Fist has introduced yet another fun new complication in the form that it actually defines every level multiple times in its RemovedFeatures and AddedFeatures List.
Someone really should have written some better checks to throw errors if that is done...

**Comment by kjk001** [comment]
Anyway onto the Shifters next...

**Comment by JohN100x1** [comment]
By the way when adding features from DLC like the shifter features then it should be done in way that will not crash for people who don't own the DLC. I discovered that some users couldn't load the mod because of the usage of DLC components. e.g. `AbilityDeliverRicochet`.

**Comment by kjk001** [comment]
I added a` if (ClassTools.Classes.ShifterClass == null) { return; }` check to do  just that.
The progression is still created(because the shifter legacy is not reliably initialized at the stage where we create the blueprint) but before class features are patched, the progression filled, and everything is added that check is called to make sure it is actually defined and loaded.

**Comment by kjk001** [comment]
And on that note I think I am done for this patch.
All remaining suggestions for legacies involve at least some degree of customization and there are now quite enough new legacies that can lead to new and unexpected bugs before I add any more.
